app_auth/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('login',login_blog,name='login-blog'),
    path('register',register,name='register'),
    path('logout',logout_blog,name='logout')
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    
    path("",views.home,name="home")

]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import home, detail, search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name="home"),
    path('article/<int:id_article>', detail, name="detail" ),
    path('article/search', search, name="search" ),
    path('auth/',include("app_auth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_admin/models.py
from django.db import models

# Create your models here.

app_auth/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models


class Category(models.Model):
    name=models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Article(models.Model):
    title=models.CharField(max_length=50)
    category =  models.ForeignKey(Category, on_delete=models.CASCADE)
    desc=models.TextField()
    image=models.ImageField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        
        return self.title

app_auth/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="username",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="password",widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="username",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="password",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(label="password confirmation",widget=forms.PasswordInput(attrs={'class':'form-control'}))

app_admin/views.py
from django.shortcuts import render

# Create your views here.

app_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *


def login_blog(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username,password=pwd)
            if user is not None:

                login(request,user)
                return redirect('home')
            else:
                messages.error(request,"Authentification not succesful")
                return render(request,'login.html',{'form':form})
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request,'login.html',{'form':form})
    else:
        form = LoginForm()
        return render(request,"login.html",{"form":form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = User.objects.create_user(username=username,password=pwd)
            if user is not None:
                return redirect("login-blog")
            else:
                messages.error(request,'account creation failed')
                return render(request,'register.html',{'form':form})
        else:
            return render(request,'register.html',{'form':form})
        return render(request,'register.html',{})

    form = RegisterForm()
    return render(request,'register.html',{'form':form})
def logout_blog(request):
    logout(request)
    #return redirect('home')
    return redirect('login-blog')

blog/views.py
from django.shortcuts import render
from .models import Article

def home(request):
    list_articles=Article.objects.all()
    context={"list_articles":list_articles}
    return render(request, "index.html",context)

def detail(request, id_article):
    article=Article.objects.get(id=id_article)
    category=article.category
    articles_in_relation=Article.objects.filter(category=category)[:5]
    return render(request, "detail.html", {"article": article,"aer": articles_in_relation})

def search(request):
    query=request.GET["article"]
    list_articles=Article.objects.filter(title__contains=query)
    return render(request, "search.html", {"list_articles":list_articles})

app_admin/templates/_navadmin.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown
          </a>
          <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default"
            aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <!--/.Navbar -->

app_admin/templates/db.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>dashboard</h2>
        </div>
    </div>
</div>
{% endblock %}

app_admin/templates/partials/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}dashboard{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <!-- Your custom styles (optional) -->
  
  
</head>
<body>
{% include '_navadmin.html' %} 
{% block content %}
{% endblock %}



    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

app_auth/templates/login.html
{% extends 'base.html' %}

{% block title %}blog connection{% endblock %}

{% block content %}

<div class="container">
    <div class="col-md-12 mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
        {% endfor %}
        {% endif %}
        <form action="" method="POST" novalidate> {% csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user"></i>blog connection</div>
                <div class="card-body">
                    <label for="id_username">username</label>
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                   <div class="div-error-{{form.pwd.errors}}"> <small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}
                    {{form.username}}

                    <label for="id_pwd">password</label>
                    {% if form.pwd.errors %}
                    {% for error in form.pwd.errors %}
                   <div class="div-error-{{form.pwd.name}}"> <small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}
                    {{form.pwd}}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">
                        log in
                    </button></div>
                    <p class="mt-2">You do not have an account? <a href="{% url 'register' %}">create account</a></p>
            </div>
        </div>
          

        </form>
        
    
</div>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function(){
        $('input').keyup(function(){
            let textsaisi = $(this).val();

            let attrName= $(this).attr('name');
            let validatorElement = ".div-error-"+attrName;
            if(textsaisi === ""){
                if(!$(this).hasClass('is-invalid')){
                    $(this).addClass('is-invalid');
                    $(validatorElement).show();
                }
            } else {
                $(this).removeClass('is-invalid');
                $(validatorElement).hide();
            }
        })
    })
</script>
{% endblock %}

app_auth/templates/register.html
{% extends 'base.html' %}

{% block title %}create acounte{% endblock %}

{% block content %}

<div class="container">
    <div class="col-md-12 mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
        {% endfor %}
        {% endif %}
        <form action="" method="POST" novalidate> {% csrf_token %}
            <div class="card">
                <div class="card-header text-center"><i class="fas fa-user-lock"></i>create acounte</div>
                <div class="card-body">
                   {{form}}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">create acounte</button></div>
            </div>
        </div>
          

        </form>
        
    
</div>
{% endblock %}
{% block scripts %}

{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My blog{% endblock %}</title>

    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript">
      var a = document.getElementById('disc-50');
      a.onclick = function () {
        Clipboard_CopyTo("T9TTVSQB");
        var div = document.getElementById('code-success');
        div.style.display = 'block';
        setTimeout(function () {
          document.getElementById('code-success').style.display = 'none';
        }, 900);
      };

      function Clipboard_CopyTo(value) {
        var tempInput = document.createElement("input");
        tempInput.value = value;
        document.body.appendChild(tempInput);
        tempInput.select();
        document.execCommand("copy");
        document.body.removeChild(tempInput);
      }
    </script>
</body>
</html>

blog/templates/brouillant.html
    {% include 'nav.html' %}
    <h1 class="text-center mt-2">Detail article</h1>
    <img src="{{article.image.url}}" alt="">
    <h2>{{article.title}}</h2>
    <p>{{article.desc}}</p>










    <a href="{% url 'detail' article.id %}">
        <img class="card-img-top" src="https://via.placeholder.com/150" alt="Card image cap" style="height: 200px;">
      </a>


      https://via.placeholder.com/150

blog/templates/detail.html
{% extends 'base.html'%}
    
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="text-center mt-2">Detail article</h1>
    <img src="{{article.image.url}}" alt="" style="max-width: 400px;">
    <h2>{{article.title}}</h2>
    <p>{{article.desc}}</p>
        </div>
        <div class="col-md-4">
            <h3 class="mt-2">articles in relations</h3>
            <div class="row">
                {% for art in aer %}
                {% if art.id != article.id %}
               
            
                <div class="col-md-7 mb-2">
                    {% if art.image != "http://default" %}
                    <img src="{{art.image.url}}" alt="" style="max-width: 185px;">
                    {% else %}
                    <img class="card-img-top" src="https://via.placeholder.com/400x300" alt="Card image cap" style="max-width: 185px;">
                    {% endif %}

                </div>
                
                <div class="col-5">
                   <strong>{{art.title}}</strong><br>
                    {{art.desc | truncatewords:7}}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

blog/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-4 mx-auto">
  
          <!-- Content -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
          <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
            consectetur
            adipisicing elit.</p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <hr>
  
    <!-- Call to action -->
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1">Register for free</h5>
      </li>
      <li class="list-inline-item">
        <a href="#!" class="btn btn-danger btn-rounded">Sign up!</a>
      </li>
    </ul>
    <!-- Call to action -->
  
    <hr>
  
    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center mt-3">welcome to our blog</h1>
      <div class="container">
      <div class="row">
          {% for article in list_articles %}
          <div class="col-12 col-md-6 col-lg-3 col-xl-3">
            <div class="card mb-2 p-2">

                <!-- Card image -->
                {% if article.image == "http://default" %}
                <a href="{% url 'detail' article.id %}">
                  <img class="card-img-top" src="{% static 'img/logo.png' %}" alt="Card image cap" style="height: 200px;">
                </a>

                {% else %}
              

                <a href="{% url 'detail' article.id %}">
                  <img class="card-img-top" src="{{article.image.url}}" alt="Card image cap" style="height: 200px;">
                </a>
                {% endif %}
               
                <!-- Card content -->
                <div class="card-body" style="height: 250px;">
              
                  <!-- Title -->
                  <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{article.title}}</a></h4>
                  <!-- Text -->
                  <p class="card-text">{{article.desc | truncatewords:6}}</p>
                  <p class="card-text">publish since {{article.created_at | timesince}}</p>
                  <!-- Button -->
                  <a href="{% url 'detail' article.id %}" class="btn btn-primary">Read more</a>
              
                </div>
              
              </div>
          </div>
        
          {% endfor %}
      </div>
      </div>
{% endblock %}

blog/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">My blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Admin<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My count
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        
      </ul>
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}" class="btn btn-info">logout</a>
      {% else %}
      <a href="{% url 'login-blog' %}" class="btn btn-info">login</a>
      {% endif %}
      <form class="form-inline" action="{% url 'search' %}">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="article">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

blog/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>list of search</h2>
    <div class="row">

        {% for article in list_articles %}
        <div class="col-12 col-md-6 col-lg-3 col-xl-3">
            <div class="card mb-2 p-2">

                <!-- Card image -->
                {% if article.image == "http://default" %}
                <a href="{% url 'detail' article.id %}">
                  <img class="card-img-top" src="{% static 'img/logo.png' %}" alt="Card image cap" style="height: 200px;">
                </a>

                {% else %}
              

                <a href="{% url 'detail' article.id %}">
                  <img class="card-img-top" src="{{article.image.url}}" alt="Card image cap" style="height: 200px;">
                </a>
                {% endif %}
               
                <!-- Card content -->
                <div class="card-body" style="height: 250px;">
              
                  <!-- Title -->
                  <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{article.title}}</a></h4>
                  <!-- Text -->
                  <p class="card-text">{{article.desc | truncatewords:6}}</p>
                  <p class="card-text">publish since {{article.created_at | timesince}}</p>
                  <!-- Button -->
                  <a href="{% url 'detail' article.id %}" class="btn btn-primary">Read more</a>
              
                </div>
              
              </div>
          </div>
        {% endfor %}
    </div>

</div>
{% endblock %}